### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by pawelkw** [arturbosch/detekt-intellij-plugin#1]
I run
```
./gradlew buildPlugin
```

```
detekt-intellij-plugin-master/src/main/java/io/gitlab/arturbosch/detekt/config/DetektConfigurationForm.form: Class not found: javax.swing.JPanel
```

Tried clean. Doesn't help.

**Comment by deeprim** [comment]
Hi @pawelkw ,

Is your JAVA_HOME pointing to JDK8?

**Comment by arturbosch** [comment]
You need to use jdk8 to build the plugin as intellij itself does not support jdk-versions > 8.
JPanel for example is now in java.desktop module.
