### ISSUE TITLE
Don't use internal com.intellij.diagnostic.ITNReporter

### ISSUE THREAD

**Issue by chashnikov** [arturbosch/detekt-intellij-plugin#18]
The plugin has `<errorHandler implementation="com.intellij.diagnostic.ITNReporter"/>` in its `plugin.xml` file. This class sends exceptions thrown from the plugin code to JetBrains for internal processing, and it isn't supposed to be used by third-party plugins. Please remove this line. BTW this line should be highlighted as an error when you open `plugin.xml` in recent versions of IntelliJ IDEA.

If you want to provide exception reporting for your plugin you need to create your own implementation of `com.intellij.openapi.diagnostic.ErrorReportSubmitter`.

**Comment by arturbosch** [comment]
Thank you for clarification. Will update asap.
