### ISSUE TITLE
no possibility to specify the baseline.xml

### ISSUE THREAD

**Issue by pjmeisch-cc** [arturbosch/detekt-intellij-plugin#24]
For running from gradle I have a detekt-baseline.xml file. The plugin does not know about this, so blacklisting files in the baseline has no effekt for the plugin.
Is it possible to add a configuration for the baseline as well?

**Comment by arturbosch** [comment]
Yep, good idea. Ideally we should pick up the baseline in `$root/detekt/baseline.xml` when not specified.

**Comment by pjmeisch-cc** [comment]
best would be if the gradle configuration could be picked up. I know of a project with subprojects, where a different baseline is kept for each subproject; tricky case.

**Comment by bagage** [comment]
I started to look at it but it implies modification to detekt repository as well, since `ProcessingSettings` does not expose baseline yet.

**Comment by arturbosch** [comment]
Take a look at https://github.com/arturbosch/detekt/blob/3543c2fe1aa46b579aac61371a13b9faf23c6e95/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/baseline/BaselineFacade.kt

The core module does not know about a baseline and though does not `ProcessingSettings`.
The cli module post process the findings like via the `BaselineFacade`. Hope that helps.
Thanks for your work!
