### ISSUE TITLE
Upgrade embedded Detekt to latest (1.0.0-RC13 now)

### ISSUE THREAD

**Issue by mikezx6r** [arturbosch/detekt-intellij-plugin#25]
I'm working on PR for this right now

**Comment by arturbosch** [comment]
Idk if anything is wrong with my ide setup or repository, but I cannot resolve the detekt dependences anymore.
Something like:
```
e: /home/abosch/Repos/detekt-intellij-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/config/NoAutoCorrectConfig.kt: (10, 57): Only interfaces can be delegated to
e: /home/abosch/Repos/detekt-intellij-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/config/NoAutoCorrectConfig.kt: (10, 57): Unresolved reference: Config
e: /home/abosch/Repos/detekt-intellij-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/config/NoAutoCorrectConfig.kt: (12, 2): 'valueOrDefault' overrides nothing
> Task :compileKotlin FAILED
```
It already happened before your upgrade ... need time to investigate this before I can release a new version, sorry.

**Comment by WonderCsabo** [comment]
@arturbosch can you release the plugin to? The current available version uses a really old version of detekt :(.

**Comment by mikezx6r** [comment]
To all those wanting a newer version of the plugin, unfortunately, @arturbosch ran into issues attempting to create this, so has not released it yet.

If you want to run it now, clone the repo, build the plugin locally, and then in IntelliJ, you can use the `Install plugin from disk` option. 

That's what I did, so I'm running this version of the plugin.

**Comment by arturbosch** [comment]
Thanks for your patience. I uploaded a new version based on detekt RC14.
Is up on github and up on jetbrains plugins portal in ~1 day.
