### ISSUE TITLE
IDEA plugin doesn't handle relative config file path

### ISSUE THREAD

**Issue by remal** [arturbosch/detekt-intellij-plugin#29]
I'd like to define configuration file path as relative path to project root. But in this case I'm getting an exception:
```
com.beust.jcommander.ParameterException: Provided path 'detekt-config.yml' does not exist!
```

I've tried all these variants and all of them don't work:

* `detekt-config.yml`
* `./detekt-config.yml`
* `$PROJECT_DIR$/detekt-config.yml`

Please resolve configuration path against project root dir.

**Comment by arturbosch** [comment]
Thanks for the suggestion!
