### ISSUE TITLE
Android Studio highlighting issue for excluded files

### ISSUE THREAD

**Issue by schauersbergern** [arturbosch/detekt-intellij-plugin#31]
Files in the path of the "excludes:" in the detekt-config.yml are still checked against
the rule, so the line with the rule violation is still highlighted

I have set up a minimal detekt project:
https://github.com/schauersbergern/detektMinimalSetup

Highlighting cannot be suppressed for the files in the excludes, e.g test, androidTest

![image](https://user-images.githubusercontent.com/22813752/60493832-f5492e80-9cad-11e9-8cd9-9316211dc311.png)

![image](https://user-images.githubusercontent.com/22813752/60493696-b2875680-9cad-11e9-9208-ee84a8b2cbec.png)

**Comment by schalkms** [comment]
Thanks for creating a sample project!
Since RC15 detekt has the includes and excludes patterns.
The plugin has also needs to support that.

**Comment by schalkms** [comment]
Btw which version of detekt's plugin do you use? 
I suppose you use v0.2.2.
Unfortunately, this version wraps the RC14 of detekt, which has no support for the includes and excludes patterns.
Thus, we need to release a new version of this plugin.

**Comment by schauersbergern** [comment]
yes, its the actual v0.2.2.

**Comment by schalkms** [comment]
@arturbosch could you please merge #32 and publish a new version to the JetBrains plugin repo?

**Comment by arturbosch** [comment]
Japp, will so asap, thanks for the effort !

**Comment by schalkms** [comment]
A new version of the IntelliJ plugin (0.3.0) including the latest version of detekt is out.

@arturbosch please close this, since I don't have the sufficient rights to do so.

**Comment by schalkms** [comment]
A new version of the IntelliJ plugin (0.3.0) including the latest version of detekt is out.

@arturbosch please close this, since I don't have the sufficient rights to do so.

**Comment by arturbosch** [comment]
@schalkms did, thanks for the reminder. However I already invited you long time ago as collaborator to this repo. Just accept it ;)

**Comment by schalkms** [comment]
This got completely lost in my mailbox. Thanks for the reminder!

**Comment by schauersbergern** [comment]
@arturbosch, @schalkms, thanks for the enhancement, you are awesome!
