### ISSUE TITLE
Detekt plugin not able to download from Maven central

### ISSUE THREAD

**Issue by ruchirnaphade** [arturbosch/detekt-intellij-plugin#36]
I am working with Kotlin and want to do static analysis using Detekt plugin. My problem is, when I want to download it from Maven central repository, it is giving me below error. But when I use company's repository (Nexus), it does not give me any error and downloads it smoothly. I don't understand this.

Can someone tell me why this is happening? I want to use this plugin and have not found out any other alternative.

Error :

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (detekt) on project agathe: Execution detekt of goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.8 or one of its dependencies could not be resolved: Could not find artifact com.beust:jcommander:jar:1.74 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

<properties>
    .. 
    <sonar.kotlin.detekt.reportPaths>${project.build.directory}/detekt.xml</sonar.kotlin.detekt.reportPaths>
    ..
</properties>

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>1.8</version>
            <executions>
                <execution>
                    
                    <id>detekt</id>
                    <phase>verify</phase>
                    <configuration>
                        <target name="detekt">
                            <java taskname="detekt" dir="${basedir}"
                                  fork="true"
                                  failonerror="false"
                                  classname="io.gitlab.arturbosch.detekt.cli.Main"
                                  classpathref="maven.plugin.classpath">
                                <arg value="--input"/>
                                <arg value="${basedir}/src"/>
                                <arg value="--filters"/>
                                <arg value=".*/target/.*,.*/resources/.*"/>
                                <arg value="--report"/>
                                <arg value="xml:${project.build.directory}/detekt.xml"/>
                            </java>
                        </target>
                    </configuration>
                    <goals>
                        <goal>run</goal>
                    </goals>
                </execution>
            </executions>
            <dependencies>
                <dependency>
                    <groupId>io.gitlab.arturbosch.detekt</groupId>
                    <artifactId>detekt-cli</artifactId>
                    <version>1.0.0-RC14</version>
                </dependency>
            </dependencies>
        </plugin>

**Comment by arturbosch** [comment]
Hey take a look what @schalkms mentioned here https://github.com/arturbosch/detekt/issues/1805.
Unfortunately the newer jcommander versions are not published to maven central anymore.
You will have to add jcenter as an additional repository to run detekt.
Maybe you will have more luck with https://github.com/Ozsie/detekt-maven-plugin which may have bundled everything together to maven central.

**Comment by ruchirnaphade** [comment]
@arturbosch Thanks for the reply and suggestion. I used https://github.com/Ozsie/detekt-maven-plugin but it is also giving me below error:

[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default) on project agathe: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Build failed with 55 weighted issues (threshold defined was 10). -> [Help 1]

I am quite new to Maven and all this plugin thing and trying to figure out how to resolve this error.

**Comment by schalkms** [comment]
I have answered this in https://github.com/Ozsie/detekt-maven-plugin/issues/25
