### ISSUE TITLE
Support ktlint as the code formatter

### ISSUE THREAD

**Issue by kaushalyap** [arturbosch/detekt-intellij-plugin#41]
Please allow to set ktlint as the code formatter.

**Comment by arturbosch** [comment]
This seems out of scope for the detekt intellij plugin.
However I will leave the `waiting for feedback` label on it.

**Comment by schalkms** [comment]
@kaushalyap thanks for providing feedback.
@arturbosch yes, this is out of scope. 

Maybe the ktlint guys or the community want to implement a separate IntelliJ or Eclipse plugin that provides this feature.

**Comment by kaushalyap** [comment]
I requested this because I am using both detekt and ktlint. I could format using command line but I would like to have IDE feedback. Anyway I will open an issue on ktlint repo
