### ISSUE TITLE
When I open 'Baseline File' I see my home directory instead of project directory

### ISSUE THREAD

**Issue by dlyahov** [arturbosch/detekt-intellij-plugin#49]
When I want to set Configuration File or Baseline File I want to see in the file browser window my current project directory, and not my home directory.

Steps to reproduce:
1. Open preferences window
2. Open 'Tools' > 'detekt' window
3. Click inside the 'Baseline File' element folder icon.

**Expected result:**
 You can see your directory of the current project

**Actual result:**
 You can see your home directory of the current project

![image](https://user-images.githubusercontent.com/8529665/67143604-c44d3380-f275-11e9-92f5-bbd6e2c3a249.png)

**Where is reproducible:** 
IntelliJ IDEA Ultimate Edition, version 2019.2.3
Operation system: Mac OS 10.15 Catalina

**Comment by dlyahov** [comment]
@arturbosch can you add me to contributors to this project? I have fixed that issue, and I can create PR)

**Comment by dlyahov** [comment]
@arturbosch I am glad, but I don't have permission to push the branch. It's my git log: 
![image](https://user-images.githubusercontent.com/8529665/67462320-fb419180-f647-11e9-9ef7-2cee587690f7.png)

**Comment by arturbosch** [comment]
@dlyahov you have to fork the project, do the change on your fork, push it to you work and GitHub will allow you to open a PR on this repository

https://yangsu.github.io/pull-request-tutorial/
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

I hope it helps, thx!

**Comment by dlyahov** [comment]
@arturbosch got it. It's here: #51
