### ISSUE TITLE
Publish plugin to JetBrains repository

### ISSUE THREAD

**Issue by klesniewski** [arturbosch/detekt-intellij-plugin#5]
The plugin would be very helpful to us, but I don't see it available from within IntelliJ (Settings > Plugins). Installing it manually by first building the plugin and then adding to IntelliJ is quite tedious when you want to implement it in a team. Is it possible to get it published to JetBrains repository, so that it is easy to install?

**Comment by arturbosch** [comment]
Hey, thanks for the suggestion. I just uploaded a version. Jetbrains now wants to approve the upload within two business days :)

**Comment by klesniewski** [comment]
It's on! Thanks! 🥇 I gave it a go, but it is not doing what I expected. I expected it will use Detekt for inspection, and so whichever problems Detekt highlights should be also visible within IntelliJ. However, the smells reported by Detekt are not visible in IntelliJ. Is it just not working, or is not meant to do what I expected?

**Comment by arturbosch** [comment]
Have you enabled it in the settings?

![2018-05-23-094530_956x158_scrot](https://user-images.githubusercontent.com/20924106/40410422-14400054-5e6e-11e8-9203-5be0b07696d5.png)
