### ISSUE TITLE
Cannot add multiple baselines if project is modular

### ISSUE THREAD

**Issue by adrianczuczka** [arturbosch/detekt-intellij-plugin#52]
If a project is broken down into modules, Detekt will create a baseline file for every single module. However, in the plugin settings, you can only add one module.

**Comment by arturbosch** [comment]
Are you using the gradle plugin which generates different baseline files for each module?
Imo there should only be one baseline file for the whole project.
Multiple baseline files are a shortcoming in the gradle plugin that we haven't figured out how to efficiently share the baseline file for the modules.

**Comment by adrianczuczka** [comment]
Yeah I'm currently using the gradle plugin which generates one baseline file per module. Are there any recommendations for getting around this?

**Comment by arturbosch** [comment]
My recommendation would be to create a top level `detektAll` task which runs over the whole project and generates the baseline.
The per module detekt tasks just use the generated baseline.
You can see our build.gradle file for how we achieve this. Hope it helps!

**Comment by adrianczuczka** [comment]
I'll check it out, thanks!

**Comment by adrianczuczka** [comment]
Unfortunately your `detektAll` task is in Kotlin and I'm not sure how the task would look in Groovy, is there anywhere I can find this task in Groovy? 😄

**Comment by arturbosch** [comment]
Yes, feel free to take a look at the website: https://arturbosch.github.io/detekt/groovydsl.html#defining-custom-detekt-task.

I will close this issue now as this is more a gradle plugin problem which is already tracked in the main repo.

**Comment by CapnSpellcheck** [comment]
> Yes, feel free to take a look at the website: https://arturbosch.github.io/detekt/groovydsl.html#defining-custom-detekt-task.
> 
> I will close this issue now as this is more a gradle plugin problem which is already tracked in the main repo.

That page does not load for me, can you double-check where it is now?

**Comment by cortinico** [comment]
It's here: https://detekt.dev/gradle.html#defining-custom-detekt-task
