### ISSUE TITLE
Indicate warning name in error message

### ISSUE THREAD

**Issue by gpeal** [arturbosch/detekt-intellij-plugin#6]
Thanks for your work Artur! I'm excited about experimenting with this at Airbnb.
I got the IntelliJ plugin working. However, could you indicate the error ID in the error message so people know what to suppress if they need to?

**Comment by gpeal** [comment]
@arturbosch

**Comment by arturbosch** [comment]
Hey, thanks for the suggestion.
We will now print `rule.id: rule.message`, so its easier to suppress the findings :)
