### ISSUE TITLE
Plugin extremely slow to update

### ISSUE THREAD

**Issue by gpeal** [arturbosch/detekt-intellij-plugin#7]
@arturbosch We have noticed that the IntelliJ plugin is extremely slow to pick up new changes and to go away when issues are fixed/suppressed. In addition, if code moves around, it continues to highlight the original code location even if the underlying code changed. Is the detekt plugin continually running on the entire codebase? If so, we have 1200, files and 40,000 LOC (counted by cloc) so that may be contributing.

cc @benschwab

**Comment by arturbosch** [comment]
Heyho, I'm aware that there is some kind of lag between editing and reanalyzing.
No, only the current open file gets analyzed. But the common thread pool is used to run all rules (30-70 depends on your config). Maybe this causes the overhead if IntelliJ does not use the common pool (I think they do). Need to investigate this more.

**Comment by Coletrane** [comment]
I'm seeing this issue again on: 
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1

**Comment by arturbosch** [comment]
@Coletrane do you think this is related to #57?
The analysis seems fast but out of sync sometimes.
