### ISSUE TITLE
After providing external configuration file no warnings / errors are shown

### ISSUE THREAD

**Issue by jukkasi** [arturbosch/detekt-intellij-plugin#8]
Works fine until I provide external configuration file (in this case tried https://raw.githubusercontent.com/arturbosch/detekt/805bb9c10db2e3c2e7d1e8b0110e6cd13a058804/detekt-cli/src/main/resources/default-detekt-config.yml) 

Then no more warnings or errors are shown.

**Comment by arturbosch** [comment]
Are there any messages in the status bar shown?
Do you use absolute or relative paths?
I'm getting warnings if I enter `/home/artur/Repos/detekt/detekt-cli/src/main/resources/default-detekt-config.yml` as absolute path.

**Comment by jukkasi** [comment]
It might be important here that I'm on Windows 10.

I'm using absolute file path which is provided when I use configuration file explorer (by clicking ...) to choose configuration file. The path is like `C:\work\project\backend\detekt.yml` I also tried replacing all \ with / but no luck. Also tried different relative alternatives with no luck.

No info in status bar or logs...

**Comment by arturbosch** [comment]
Hmm, unfortunately I do not have a windows system to do some tests.
Could you please test normal detekt-cli run with windows specific paths. If this works we can say it is the intellij-plugin for sure.
Next we need to find out how intellij does debugging :)

**Comment by arturbosch** [comment]
Please try again with 0.2.0.
We now use the same logic as the cli module uses which got some fixes for windows etc.

**Comment by jukkasi** [comment]
Works fine in 0.2.0
